### ISSUE TITLE
Feature request for a MFXLegacyTextField

### ISSUE THREAD

**Issue by Tech-Expert-Wizard** [palexdev/MaterialFX#184]
**Is your feature request related to a problem? Please describe.**
I don't exactly have a problem, but I find that I don't really like the new `MFXTextField` design.

**Describe the solution you'd like**
I would appreciate it if you could take the old `MFXTextField` design from version 11.12.0 and put it as a `MFXLegacyTextField`, like some other controls that have legacy versions.

**Describe alternatives you've considered**
I did consider using JFoenix, but there are many problems in using JFoenix. The other option is doing it myself, but I don't really have enough time for that.

**Comment by palexdev** [comment]
Is there anything you can't achieve with the new text field?

If you are purely talking about its style you can easily change it with CSS

**Comment by Tech-Expert-Wizard** [comment]
@palexdev Then how do I use CSS to style it like the old text field? Because I simply want the old style...

**Comment by palexdev** [comment]
This should achieve similar results:
```css
.mfx-text-field {
    -mfx-float-mode: disabled;
    -fx-padding: 0 0 3 0;
    
    -fx-background-color: transparent;
    -fx-background-radius: 0;
    -fx-background-insets: 0;

    -fx-border-color: transparent transparent lightgray transparent;
    -fx-border-radius: 0;
    -fx-border-insets: 0;
    -fx-border-width: 1.5;
}

.mfx-text-field:focus-within {
    -fx-border-color: transparent transparent -mfx-main transparent;

}

.mfx-text-field .text-field {
    -fx-highlight-fill: lightblue;
}
```
