### ISSUE TITLE
FloatingText for DatePIcker

### ISSUE THREAD

**Issue by panosru** [palexdev/MaterialFX#190]
MFXDatePicker is great, but, I would love for it to support floating text like almost all the rest of the fields.

For example, you can currently set prompt text to "Birth Date" and have a result as such:

![image](https://user-images.githubusercontent.com/400362/165757446-e6460382-5cff-41ad-bd4e-0ab0e38fa51b.png)

But, the purpose of _prompt text_ is to provide the user with info on data format or idea, like so:

![image](https://user-images.githubusercontent.com/400362/165757652-4a13048f-235c-48be-a6dd-a985eb7bc46f.png)

Once you select data, then you don't see the _prompt text_ any longer, since it isn't needed:

![image](https://user-images.githubusercontent.com/400362/165757841-a306f37d-1a1c-48ef-a7ff-75d9f17cf91b.png)

A floating text would solve that issue, for instance:

![image](https://user-images.githubusercontent.com/400362/165757941-b74d4c2e-360e-47ef-95a3-ea6258ee6324.png)

Lastly, if you have multiple date fields, one for a birth date, another for x date and y date, when you edit the date, since the floating text isn't available, your three date fields won't have any indicator for what kind of info is the displayed data referred to, only if you manually add labels and most likely won't look as nice as the other fields.

**UPDATE:**
Current workaround:

![image](https://user-images.githubusercontent.com/400362/165783049-79df2a03-d0bd-4724-a503-0b5f736d01ca.png)

![image](https://user-images.githubusercontent.com/400362/165783142-ba8b0de2-ac92-409e-909b-aa71ea3e321c.png)

FXML:
```xml
<Pane layoutX="254.0" layoutY="229.0" prefHeight="51.0" prefWidth="198.0" styleClass="fieldset">
   <children>
      <VBox alignment="CENTER">
         <HBox alignment="CENTER">
            <MFXDatePicker fx:id="birthDate" prefHeight="51.0" prefWidth="122.0" promptText="DD/MM/YYYY" />
         </HBox>
      </VBox>
      <Label layoutX="8.0" layoutY="-10.0" styleClass="fieldset-title" text="Birth Date" />
   </children>
</Pane>
```

```css
.fieldset {
    -mfx-main: -mfx-purple;
    -fx-background-color: white;
    -fx-background-radius: 5;
    -fx-border-color: lightgray;
    -fx-border-radius: 5;
    -fx-padding: 5;
}

.fieldset .fieldset-title {
    -fx-padding: 0 3;
    -fx-font-family: "Open Sans Regular";
    -fx-text-fill: -mfx-text-he;
    -fx-background-color: white;
}

.fieldset MFXDatePicker {
    -fx-border-color: transparent;
    -fx-background-color: transparent;
}
```

Unfortunately, the JavaFX CSS processor does not support `:has`, there fore something like the following isn't possible directly from CSS:

```css
.fieldset:has(.mfx-date-picker):has(:focus-within) {
    -fx-border-color: -mfx-purple;
}

.fieldset:has(.mfx-date-picker):has(:focus-within) .fieldset-title {
    -fx-text-fill: -mfx-purple;
}
```

That way, when the enclosed `MFXDatePicker` filled had `focus-within`, it would set the fieldset border and label text colour to `-mfx-purple`
