### ISSUE TITLE
MFXFieldGroup

### ISSUE THREAD

**Issue by panosru** [palexdev/MaterialFX#191]
It would be a great addition to the library if an element like `MFXFrieldGroup` was provided, it could act somehow like a `fieldset` element in HTML but with a _material_ look.

![image](https://user-images.githubusercontent.com/400362/165760376-d7cb8966-b603-4b99-be6f-c144f045d533.png)

_The screenshot does not have material look, but it provides an idea._

That would be very useful to have group fields, especially check and radio boxes that are part of a group, for example currently these groups don't provide any way to label the group, you have to place the label manually.

![image](https://user-images.githubusercontent.com/400362/165760914-e8191455-7bf1-4ce5-8e18-50cbc12090d0.png)

**UPDATE:**
Just a simple example of what I'm currently doing to  achieve the above-mentioned result:

![image](https://user-images.githubusercontent.com/400362/165776708-9764fa5b-c107-4553-8cfa-006caa346b99.png)

The fxml code:
```xml
<Pane layoutX="8.0" layoutY="225.0" prefHeight="51.0" prefWidth="231.0" styleClass="fieldset">
   <children>
      <MFXRadioButton layoutX="14.0" layoutY="17.0" text="Male">
         <toggleGroup>
            <ToggleGroup fx:id="gender" />
         </toggleGroup>
      </MFXRadioButton>
      <MFXRadioButton layoutX="111.0" layoutY="17.0" text="Female" toggleGroup="$gender" />
      <Label layoutX="8.0" layoutY="-10.0" styleClass="fieldset-title" text="Gender" />
   </children>
</Pane>
```

The CSS code:
```css
.fieldset {
    -mfx-main: -mfx-purple;
    -fx-background-color: white;
    -fx-background-radius: 5;
    -fx-border-color: lightgray;
    -fx-border-radius: 5;
    -fx-padding: 5;
}

.fieldset .fieldset-title {
    -fx-padding: 0 3;
    -fx-font-family: "Open Sans Regular";
    -fx-text-fill: -mfx-text-he;
    -fx-background-color: white;
}
```
