### ISSUE TITLE
How can I get a flat & square progress bar ?

### ISSUE THREAD

**Issue by DBChoco** [palexdev/MaterialFX#200]
## Hello there !
This is what I have:
![MFXProgressBar](https://i.imgur.com/xD3B4fD.png) 
And this is what I want:
![Bootstrap progress bar](https://i.imgur.com/B2LK0Ya.png) 

As you can see on the second image, the progress bar is flat at the bottom.
I've tried this code: 
```
#progressBar .bar, #progressBar .track {
    -fx-background-insets: 0px;
    -fx-background-radius:0;
    -fx-border-radius: 0;
}
```
But it doesn't do anything. Could you help me out please ? Thanks !
Btw, thanks a bunch for this awesome library.

**Comment by M-K-Al** [comment]
If you want a square progress bar:

```css
#progressBar .track,
#progressBar .bar1,
#progressBar .bar2 {
    -fx-arc-height: 0;
    -fx-arc-width: 0;
}
```
This the result:

![image](https://user-images.githubusercontent.com/60324664/169244922-c454d7ec-337b-4d29-a2ff-0a7b44f3ea9c.png)

But I'm not sure what you mean by a flat, from the provided image it looks like you want only the top-left & top-right corners to be rounded. This's easy to achieve in normal cases using [CornerRadii](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/layout/CornerRadii.html), but since the progress bar has many layers the easiest way to achieve this is by covering the bottom have of the progress bar. To achieve this I'll use a rectangle.

```java
final Rectangle rectangle = new Rectangle(300, 10, Color.BLACK);
rectangle.setTranslateY(10);

final MFXProgressBar progressBar = new MFXProgressBar(0.37);
progressBar.setId("progressBar");
progressBar.setPrefWidth(300);
progressBar.setPrefHeight(20);

final StackPane stackPane = new StackPane(progressBar, rectangle);
stackPane.setBackground(Background.fill(Color.BLACK));
```

```css
#progressBar .track { /* This will make the track rounded */
    -fx-arc-height: 12;
    -fx-arc-width: 12;
}

#progressBar .bar1,
#progressBar .bar2 { /* This will make the bars square */
    -fx-arc-height: 0;
    -fx-arc-width: 0;
}
```

The result:

![image](https://user-images.githubusercontent.com/60324664/169248421-d9e1d29c-112a-41b7-8907-cb9e2e5a0098.png)
